version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    ignore:
      - dependency-name: '@types/*'
      - dependency-name: '@babel/*'
      - dependency-name: 'metro-react-native-babel-preset'
