# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "mobile3.xcodeproj")
    build_app(workspace: "mobile3.xcworkspace", scheme: "mobile3")
    upload_to_testflight
  end

  desc "Discord notify"
  lane :test do
    discord_notifier(
    webhook_url:"https://discord.com/api/webhooks/1015841619548831774/ZTdFvT4KoU5Em58yTXnIuXe28nmwiA3SpTb5jd2pX_USUUUq6f9f3Ipi38TTB-kK53_d",
    title: "Fastlane",
    description: "The app has been build and submitted to testflight",
    fields: [
      {
        name:"Field1", 
        value:"Value1"
      },
      {
        name:"Field2", 
        value:"Value2",
        inline: true
      },
      {
        name:"Field3", 
        value:"Value3",
        inline: true
      }])
  end
end