name: Weekly deps upgrade alert
on:
  schedule:
    - cron: '0 13 * * 1'

jobs:
  create_issue:
    name: create-issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Issue Bot Action
        uses: imjohnbo/issue-bot@v3.3.4
        with:
          labels: 'dev, P0'
          title: 'Weekly Mobile App Dependencies Upgrade'
          body: |
            - [ ] Run command `yarn outdated` and check for the following dependencies updates available:
                  - react-native-navigation/*
            - [ ] Make a clean build including clearing the node_modules, Pods and clean the build folder xcode -> `(↑ Shift + ⌘ Cmd + K)`
            - [ ] Run command `yarn && npx pod-install && yarn ios` to test the app for any issues that may have occure
            - [ ] If everything works, create a new pr with the changes
          pinned: false
          close-previous: false
