name: Weekly Dependecies App update
on:
  schedule:
    - cron: '30 5,17 * * *'

jobs:
  create_issue:
    name: Weekly app update check
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const deps = ['react-native-camera'];

            console.log(deps);
