name: Weekly Dependecies App update
on: [push]

jobs:
  create_issue:
    name: Weekly app update check
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: fetching updates
        echo: yarn outdated eslint
      - name: Issue Bot Action
        uses: imjohnbo/issue-bot@v3.3.4
        with:
          assignees: 'twanluttik'
          labels: 'deps-update-check'
          title: 'Weekly update'
          body: |
            - [ ] Start the recording
            - [ ] Check-ins
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
