name: Weekly Dependecies App update
on: [push]

jobs:
  create_issue:
    name: Weekly app update check
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Issue Bot Action
        uses: imjohnbo/issue-bot@v3.3.4
        with:
          assignees: 'twanluttik'
          labels: 'deps-update-check'
          title: 'Weekly update'
          body: |
            - [ ] Run command `yarn outdated` and check for the following dependencies updates available:
                  - react-native-navigation/*
            - [ ] Make a clean build including clearing the node_modules, Pods and clean the build folder xcode -> `(↑ Shift + ⌘ Cmd + K)`
            - [ ] Run command `yarn && npx pod-install && yarn ios` to test the app for any issues that may have occure
            - [ ] If everything works, create a new pr with the changes
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
